//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeManager.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeManager.DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackupHomeManagerDB.
        /// </summary>
        internal static string BackupHomeManagerDB {
            get {
                return ResourceManager.GetString("BackupHomeManagerDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Account.
        /// </summary>
        internal static string D_Account {
            get {
                return ResourceManager.GetString("D_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Adressen.
        /// </summary>
        internal static string D_Adressen {
            get {
                return ResourceManager.GetString("D_Adressen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Begunstigden.
        /// </summary>
        internal static string D_Begunstigden {
            get {
                return ResourceManager.GetString("D_Begunstigden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_BudgetBijlage.
        /// </summary>
        internal static string D_BudgetBijlage {
            get {
                return ResourceManager.GetString("D_BudgetBijlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_BudgetCategorie.
        /// </summary>
        internal static string D_BudgetCategorie {
            get {
                return ResourceManager.GetString("D_BudgetCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_BudgetTransaction.
        /// </summary>
        internal static string D_BudgetTransaction {
            get {
                return ResourceManager.GetString("D_BudgetTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Dagboek.
        /// </summary>
        internal static string D_Dagboek {
            get {
                return ResourceManager.GetString("D_Dagboek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Domiciliering.
        /// </summary>
        internal static string D_Domiciliering {
            get {
                return ResourceManager.GetString("D_Domiciliering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_DomicilieringMetTransacties.
        /// </summary>
        internal static string D_DomicilieringMetTransacties {
            get {
                return ResourceManager.GetString("D_DomicilieringMetTransacties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_EmailAdressen.
        /// </summary>
        internal static string D_EmailAdressen {
            get {
                return ResourceManager.GetString("D_EmailAdressen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_EmailType.
        /// </summary>
        internal static string D_EmailType {
            get {
                return ResourceManager.GetString("D_EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Frequentie.
        /// </summary>
        internal static string D_Frequentie {
            get {
                return ResourceManager.GetString("D_Frequentie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Functies.
        /// </summary>
        internal static string D_Functies {
            get {
                return ResourceManager.GetString("D_Functies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Gemeente.
        /// </summary>
        internal static string D_Gemeente {
            get {
                return ResourceManager.GetString("D_Gemeente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Land.
        /// </summary>
        internal static string D_Land {
            get {
                return ResourceManager.GetString("D_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Notities.
        /// </summary>
        internal static string D_Notities {
            get {
                return ResourceManager.GetString("D_Notities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Persoon.
        /// </summary>
        internal static string D_Persoon {
            get {
                return ResourceManager.GetString("D_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Provincie.
        /// </summary>
        internal static string D_Provincie {
            get {
                return ResourceManager.GetString("D_Provincie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Rollen.
        /// </summary>
        internal static string D_Rollen {
            get {
                return ResourceManager.GetString("D_Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_StickyNotes.
        /// </summary>
        internal static string D_StickyNotes {
            get {
                return ResourceManager.GetString("D_StickyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_TelefoonNummers.
        /// </summary>
        internal static string D_TelefoonNummers {
            get {
                return ResourceManager.GetString("D_TelefoonNummers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_TelefoonType.
        /// </summary>
        internal static string D_TelefoonType {
            get {
                return ResourceManager.GetString("D_TelefoonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_ToDoBijlage.
        /// </summary>
        internal static string D_ToDoBijlage {
            get {
                return ResourceManager.GetString("D_ToDoBijlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_ToDoCategorieën.
        /// </summary>
        internal static string D_ToDoCategorieën {
            get {
                return ResourceManager.GetString("D_ToDoCategorieën", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_TodoCollecties.
        /// </summary>
        internal static string D_ToDoCollecties {
            get {
                return ResourceManager.GetString("D_ToDoCollecties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_ToDoDetails.
        /// </summary>
        internal static string D_ToDoDetails {
            get {
                return ResourceManager.GetString("D_ToDoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_ToDoKLeuren.
        /// </summary>
        internal static string D_ToDoKLeuren {
            get {
                return ResourceManager.GetString("D_ToDoKLeuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_ToDoPopup.
        /// </summary>
        internal static string D_ToDoPopup {
            get {
                return ResourceManager.GetString("D_ToDoPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Wachtwoord.
        /// </summary>
        internal static string D_Wachtwoord {
            get {
                return ResourceManager.GetString("D_Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_WachtWoordenGroep.
        /// </summary>
        internal static string D_WachtWoordenGroep {
            get {
                return ResourceManager.GetString("D_WachtWoordenGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Account.
        /// </summary>
        internal static string I_Account {
            get {
                return ResourceManager.GetString("I_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Adressen.
        /// </summary>
        internal static string I_Adressen {
            get {
                return ResourceManager.GetString("I_Adressen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Begunstigden.
        /// </summary>
        internal static string I_Begunstigden {
            get {
                return ResourceManager.GetString("I_Begunstigden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_BudgetBijlage.
        /// </summary>
        internal static string I_BudgetBijlage {
            get {
                return ResourceManager.GetString("I_BudgetBijlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_BudgetCategorie.
        /// </summary>
        internal static string I_BudgetCategorie {
            get {
                return ResourceManager.GetString("I_BudgetCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_BudgetTransaction.
        /// </summary>
        internal static string I_BudgetTransaction {
            get {
                return ResourceManager.GetString("I_BudgetTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_ButtonLog.
        /// </summary>
        internal static string I_ButtonLog {
            get {
                return ResourceManager.GetString("I_ButtonLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Dagboek.
        /// </summary>
        internal static string I_Dagboek {
            get {
                return ResourceManager.GetString("I_Dagboek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Domiciliering.
        /// </summary>
        internal static string I_Domiciliering {
            get {
                return ResourceManager.GetString("I_Domiciliering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_DomicilieringMetTransacties.
        /// </summary>
        internal static string I_DomicilieringMetTransacties {
            get {
                return ResourceManager.GetString("I_DomicilieringMetTransacties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_EmailAdressen.
        /// </summary>
        internal static string I_EmailAdressen {
            get {
                return ResourceManager.GetString("I_EmailAdressen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_EmailType.
        /// </summary>
        internal static string I_EmailType {
            get {
                return ResourceManager.GetString("I_EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_ExceptionLog.
        /// </summary>
        internal static string I_ExceptionLog {
            get {
                return ResourceManager.GetString("I_ExceptionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Frequentie.
        /// </summary>
        internal static string I_Frequentie {
            get {
                return ResourceManager.GetString("I_Frequentie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Functies.
        /// </summary>
        internal static string I_Functies {
            get {
                return ResourceManager.GetString("I_Functies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Gemeente.
        /// </summary>
        internal static string I_Gemeente {
            get {
                return ResourceManager.GetString("I_Gemeente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Land.
        /// </summary>
        internal static string I_Land {
            get {
                return ResourceManager.GetString("I_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Notities.
        /// </summary>
        internal static string I_Notities {
            get {
                return ResourceManager.GetString("I_Notities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Persoon.
        /// </summary>
        internal static string I_Persoon {
            get {
                return ResourceManager.GetString("I_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Provincie.
        /// </summary>
        internal static string I_Provincie {
            get {
                return ResourceManager.GetString("I_Provincie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Rollen.
        /// </summary>
        internal static string I_Rollen {
            get {
                return ResourceManager.GetString("I_Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_StickyNotes.
        /// </summary>
        internal static string I_StickyNotes {
            get {
                return ResourceManager.GetString("I_StickyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_TelefoonNummers.
        /// </summary>
        internal static string I_TelefoonNummers {
            get {
                return ResourceManager.GetString("I_TelefoonNummers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_TelefoonType.
        /// </summary>
        internal static string I_TelefoonType {
            get {
                return ResourceManager.GetString("I_TelefoonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_ToDoBijlage.
        /// </summary>
        internal static string I_ToDoBijlage {
            get {
                return ResourceManager.GetString("I_ToDoBijlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_ToDoCategorieën.
        /// </summary>
        internal static string I_ToDoCategorieën {
            get {
                return ResourceManager.GetString("I_ToDoCategorieën", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_ToDoCollecties.
        /// </summary>
        internal static string I_ToDoCollecties {
            get {
                return ResourceManager.GetString("I_ToDoCollecties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_ToDoDetails.
        /// </summary>
        internal static string I_ToDoDetails {
            get {
                return ResourceManager.GetString("I_ToDoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_ToDoKLeuren.
        /// </summary>
        internal static string I_ToDoKLeuren {
            get {
                return ResourceManager.GetString("I_ToDoKLeuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_ToDoPopup.
        /// </summary>
        internal static string I_ToDoPopup {
            get {
                return ResourceManager.GetString("I_ToDoPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Wachtwoord.
        /// </summary>
        internal static string I_Wachtwoord {
            get {
                return ResourceManager.GetString("I_Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_WachtWoordenGroep.
        /// </summary>
        internal static string I_WachtWoordenGroep {
            get {
                return ResourceManager.GetString("I_WachtWoordenGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Account.
        /// </summary>
        internal static string S_Account {
            get {
                return ResourceManager.GetString("S_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Adressen.
        /// </summary>
        internal static string S_Adressen {
            get {
                return ResourceManager.GetString("S_Adressen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_AdressenByID.
        /// </summary>
        internal static string S_AdressenByID {
            get {
                return ResourceManager.GetString("S_AdressenByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Begunstigden.
        /// </summary>
        internal static string S_Begunstigden {
            get {
                return ResourceManager.GetString("S_Begunstigden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_BudgetBijlageByBudgetTransactionID.
        /// </summary>
        internal static string S_BudgetBijlageByBudgetTransactionID {
            get {
                return ResourceManager.GetString("S_BudgetBijlageByBudgetTransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_BudgetCategorie.
        /// </summary>
        internal static string S_BudgetCategorie {
            get {
                return ResourceManager.GetString("S_BudgetCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_BudgetOverzichtInkomsten.
        /// </summary>
        internal static string S_BudgetOverzichtInkomsten {
            get {
                return ResourceManager.GetString("S_BudgetOverzichtInkomsten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_BudgetOverzichtInkomstenV1.
        /// </summary>
        internal static string S_BudgetOverzichtInkomstenV1 {
            get {
                return ResourceManager.GetString("S_BudgetOverzichtInkomstenV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_BudgetOverzichtUitgaven.
        /// </summary>
        internal static string S_BudgetOverzichtUitgaven {
            get {
                return ResourceManager.GetString("S_BudgetOverzichtUitgaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_BudgetTransaction.
        /// </summary>
        internal static string S_BudgetTransaction {
            get {
                return ResourceManager.GetString("S_BudgetTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ButtonLogsByAccountId.
        /// </summary>
        internal static string S_ButtonLogsByAccountId {
            get {
                return ResourceManager.GetString("S_ButtonLogsByAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ButtonLogsByActionName.
        /// </summary>
        internal static string S_ButtonLogsByActionName {
            get {
                return ResourceManager.GetString("S_ButtonLogsByActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ButtonLogsByActionTarget.
        /// </summary>
        internal static string S_ButtonLogsByActionTarget {
            get {
                return ResourceManager.GetString("S_ButtonLogsByActionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ButtonLogsByDate.
        /// </summary>
        internal static string S_ButtonLogsByDate {
            get {
                return ResourceManager.GetString("S_ButtonLogsByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ButtonLogsFirst1000.
        /// </summary>
        internal static string S_ButtonLogsFirst1000 {
            get {
                return ResourceManager.GetString("S_ButtonLogsFirst1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Dagboek.
        /// </summary>
        internal static string S_Dagboek {
            get {
                return ResourceManager.GetString("S_Dagboek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Domiciliering.
        /// </summary>
        internal static string S_Domiciliering {
            get {
                return ResourceManager.GetString("S_Domiciliering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_EmailAdressen.
        /// </summary>
        internal static string S_EmailAdressen {
            get {
                return ResourceManager.GetString("S_EmailAdressen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_EmailAdressenByID.
        /// </summary>
        internal static string S_EmailAdressenByID {
            get {
                return ResourceManager.GetString("S_EmailAdressenByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_EmailAdressenByRolName.
        /// </summary>
        internal static string S_EmailAdressenByRolName {
            get {
                return ResourceManager.GetString("S_EmailAdressenByRolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_EmailType.
        /// </summary>
        internal static string S_EmailType {
            get {
                return ResourceManager.GetString("S_EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ExceptionsByAccountID.
        /// </summary>
        internal static string S_ExceptionsByAccountID {
            get {
                return ResourceManager.GetString("S_ExceptionsByAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ExceptionsByDate.
        /// </summary>
        internal static string S_ExceptionsByDate {
            get {
                return ResourceManager.GetString("S_ExceptionsByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ExceptionsByExceptionName.
        /// </summary>
        internal static string S_ExceptionsByExceptionName {
            get {
                return ResourceManager.GetString("S_ExceptionsByExceptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ExceptionsByTargetSite.
        /// </summary>
        internal static string S_ExceptionsByTargetSite {
            get {
                return ResourceManager.GetString("S_ExceptionsByTargetSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ExceptionsFirst1000.
        /// </summary>
        internal static string S_ExceptionsFirst1000 {
            get {
                return ResourceManager.GetString("S_ExceptionsFirst1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Frequentie.
        /// </summary>
        internal static string S_Frequentie {
            get {
                return ResourceManager.GetString("S_Frequentie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Functies.
        /// </summary>
        internal static string S_Functies {
            get {
                return ResourceManager.GetString("S_Functies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Gemeente.
        /// </summary>
        internal static string S_Gemeente {
            get {
                return ResourceManager.GetString("S_Gemeente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Land.
        /// </summary>
        internal static string S_Land {
            get {
                return ResourceManager.GetString("S_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_LockedUsers.
        /// </summary>
        internal static string S_LockedUsers {
            get {
                return ResourceManager.GetString("S_LockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Login.
        /// </summary>
        internal static string S_Login {
            get {
                return ResourceManager.GetString("S_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Notities.
        /// </summary>
        internal static string S_Notities {
            get {
                return ResourceManager.GetString("S_Notities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_NotitiesByID.
        /// </summary>
        internal static string S_NotitiesByID {
            get {
                return ResourceManager.GetString("S_NotitiesByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Persoon.
        /// </summary>
        internal static string S_Persoon {
            get {
                return ResourceManager.GetString("S_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Provincie.
        /// </summary>
        internal static string S_Provincie {
            get {
                return ResourceManager.GetString("S_Provincie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Rechten.
        /// </summary>
        internal static string S_Rechten {
            get {
                return ResourceManager.GetString("S_Rechten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_RechtenCatogorie.
        /// </summary>
        internal static string S_RechtenCatogorie {
            get {
                return ResourceManager.GetString("S_RechtenCatogorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Rollen.
        /// </summary>
        internal static string S_Rollen {
            get {
                return ResourceManager.GetString("S_Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_StickyNotes.
        /// </summary>
        internal static string S_StickyNotes {
            get {
                return ResourceManager.GetString("S_StickyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_StickyNotesByID.
        /// </summary>
        internal static string S_StickyNotesByID {
            get {
                return ResourceManager.GetString("S_StickyNotesByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_TelefoonNummerByID.
        /// </summary>
        internal static string S_TelefoonNummerByID {
            get {
                return ResourceManager.GetString("S_TelefoonNummerByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_TelefoonNummers.
        /// </summary>
        internal static string S_TelefoonNummers {
            get {
                return ResourceManager.GetString("S_TelefoonNummers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_TelefoonType.
        /// </summary>
        internal static string S_TelefoonType {
            get {
                return ResourceManager.GetString("S_TelefoonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ToDoBijlage.
        /// </summary>
        internal static string S_ToDoBijlage {
            get {
                return ResourceManager.GetString("S_ToDoBijlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ToDoCategorieën.
        /// </summary>
        internal static string S_ToDoCategorieën {
            get {
                return ResourceManager.GetString("S_ToDoCategorieën", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ToDoCollecties.
        /// </summary>
        internal static string S_ToDoCollecties {
            get {
                return ResourceManager.GetString("S_ToDoCollecties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ToDoDetails.
        /// </summary>
        internal static string S_ToDoDetails {
            get {
                return ResourceManager.GetString("S_ToDoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ToDoKLeuren.
        /// </summary>
        internal static string S_ToDoKLeuren {
            get {
                return ResourceManager.GetString("S_ToDoKLeuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ToDoPopup.
        /// </summary>
        internal static string S_ToDoPopup {
            get {
                return ResourceManager.GetString("S_ToDoPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Wachtwoord.
        /// </summary>
        internal static string S_Wachtwoord {
            get {
                return ResourceManager.GetString("S_Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_WachtWoordenGroep.
        /// </summary>
        internal static string S_WachtWoordenGroep {
            get {
                return ResourceManager.GetString("S_WachtWoordenGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Account.
        /// </summary>
        internal static string U_Account {
            get {
                return ResourceManager.GetString("U_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Adressen.
        /// </summary>
        internal static string U_Adressen {
            get {
                return ResourceManager.GetString("U_Adressen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Begunstigden.
        /// </summary>
        internal static string U_Begunstigden {
            get {
                return ResourceManager.GetString("U_Begunstigden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_BudgetCategorie.
        /// </summary>
        internal static string U_BudgetCategorie {
            get {
                return ResourceManager.GetString("U_BudgetCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_BudgetTransaction.
        /// </summary>
        internal static string U_BudgetTransaction {
            get {
                return ResourceManager.GetString("U_BudgetTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Dagboek.
        /// </summary>
        internal static string U_Dagboek {
            get {
                return ResourceManager.GetString("U_Dagboek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Domiciliering.
        /// </summary>
        internal static string U_Domiciliering {
            get {
                return ResourceManager.GetString("U_Domiciliering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_EmailAdressen.
        /// </summary>
        internal static string U_EmailAdressen {
            get {
                return ResourceManager.GetString("U_EmailAdressen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_EmailType.
        /// </summary>
        internal static string U_EmailType {
            get {
                return ResourceManager.GetString("U_EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Frequentie.
        /// </summary>
        internal static string U_Frequentie {
            get {
                return ResourceManager.GetString("U_Frequentie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Functies.
        /// </summary>
        internal static string U_Functies {
            get {
                return ResourceManager.GetString("U_Functies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Gemeente.
        /// </summary>
        internal static string U_Gemeente {
            get {
                return ResourceManager.GetString("U_Gemeente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Land.
        /// </summary>
        internal static string U_Land {
            get {
                return ResourceManager.GetString("U_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_LockedUsers.
        /// </summary>
        internal static string U_LockedUsers {
            get {
                return ResourceManager.GetString("U_LockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Login.
        /// </summary>
        internal static string U_Login {
            get {
                return ResourceManager.GetString("U_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Notities.
        /// </summary>
        internal static string U_Notities {
            get {
                return ResourceManager.GetString("U_Notities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Persoon.
        /// </summary>
        internal static string U_Persoon {
            get {
                return ResourceManager.GetString("U_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Provincie.
        /// </summary>
        internal static string U_Provincie {
            get {
                return ResourceManager.GetString("U_Provincie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Rollen.
        /// </summary>
        internal static string U_Rollen {
            get {
                return ResourceManager.GetString("U_Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_StickyNotes.
        /// </summary>
        internal static string U_StickyNotes {
            get {
                return ResourceManager.GetString("U_StickyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_TelefoonNummers.
        /// </summary>
        internal static string U_TelefoonNummers {
            get {
                return ResourceManager.GetString("U_TelefoonNummers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_TelefoonType.
        /// </summary>
        internal static string U_TelefoonType {
            get {
                return ResourceManager.GetString("U_TelefoonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_ToDoBijlage.
        /// </summary>
        internal static string U_ToDoBijlage {
            get {
                return ResourceManager.GetString("U_ToDoBijlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_ToDoCategorieën.
        /// </summary>
        internal static string U_ToDoCategorieën {
            get {
                return ResourceManager.GetString("U_ToDoCategorieën", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_ToDoCollecties.
        /// </summary>
        internal static string U_ToDoCollecties {
            get {
                return ResourceManager.GetString("U_ToDoCollecties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_ToDoDetails.
        /// </summary>
        internal static string U_ToDoDetails {
            get {
                return ResourceManager.GetString("U_ToDoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_ToDoKLeuren.
        /// </summary>
        internal static string U_ToDoKLeuren {
            get {
                return ResourceManager.GetString("U_ToDoKLeuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_ToDoPopup.
        /// </summary>
        internal static string U_ToDoPopup {
            get {
                return ResourceManager.GetString("U_ToDoPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_UpdateDomicilieringMetTransacties.
        /// </summary>
        internal static string U_UpdateDomicilieringMetTransacties {
            get {
                return ResourceManager.GetString("U_UpdateDomicilieringMetTransacties", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Wachtwoord.
        /// </summary>
        internal static string U_Wachtwoord {
            get {
                return ResourceManager.GetString("U_Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_WachtWoordenGroep.
        /// </summary>
        internal static string U_WachtWoordenGroep {
            get {
                return ResourceManager.GetString("U_WachtWoordenGroep", resourceCulture);
            }
        }
    }
}
