//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeManager.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeManager.DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Account.
        /// </summary>
        internal static string D_Account {
            get {
                return ResourceManager.GetString("D_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Begunstigden.
        /// </summary>
        internal static string D_Begunstigden {
            get {
                return ResourceManager.GetString("D_Begunstigden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_BudgetCategorie.
        /// </summary>
        internal static string D_BudgetCategorie {
            get {
                return ResourceManager.GetString("D_BudgetCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Domiciliering.
        /// </summary>
        internal static string D_Domiciliering {
            get {
                return ResourceManager.GetString("D_Domiciliering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Frequentie.
        /// </summary>
        internal static string D_Frequentie {
            get {
                return ResourceManager.GetString("D_Frequentie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Persoon.
        /// </summary>
        internal static string D_Persoon {
            get {
                return ResourceManager.GetString("D_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Rollen.
        /// </summary>
        internal static string D_Rollen {
            get {
                return ResourceManager.GetString("D_Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Wachtwoord.
        /// </summary>
        internal static string D_Wachtwoord {
            get {
                return ResourceManager.GetString("D_Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_WachtWoordenGroep.
        /// </summary>
        internal static string D_WachtWoordenGroep {
            get {
                return ResourceManager.GetString("D_WachtWoordenGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Account.
        /// </summary>
        internal static string I_Account {
            get {
                return ResourceManager.GetString("I_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Begunstigden.
        /// </summary>
        internal static string I_Begunstigden {
            get {
                return ResourceManager.GetString("I_Begunstigden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_BudgetCategorie.
        /// </summary>
        internal static string I_BudgetCategorie {
            get {
                return ResourceManager.GetString("I_BudgetCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Domiciliering.
        /// </summary>
        internal static string I_Domiciliering {
            get {
                return ResourceManager.GetString("I_Domiciliering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Frequentie.
        /// </summary>
        internal static string I_Frequentie {
            get {
                return ResourceManager.GetString("I_Frequentie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Persoon.
        /// </summary>
        internal static string I_Persoon {
            get {
                return ResourceManager.GetString("I_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Rollen.
        /// </summary>
        internal static string I_Rollen {
            get {
                return ResourceManager.GetString("I_Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Wachtwoord.
        /// </summary>
        internal static string I_Wachtwoord {
            get {
                return ResourceManager.GetString("I_Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_WachtWoordenGroep.
        /// </summary>
        internal static string I_WachtWoordenGroep {
            get {
                return ResourceManager.GetString("I_WachtWoordenGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Account.
        /// </summary>
        internal static string S_Account {
            get {
                return ResourceManager.GetString("S_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Begunstigden.
        /// </summary>
        internal static string S_Begunstigden {
            get {
                return ResourceManager.GetString("S_Begunstigden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_BudgetCategorie.
        /// </summary>
        internal static string S_BudgetCategorie {
            get {
                return ResourceManager.GetString("S_BudgetCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Domiciliering.
        /// </summary>
        internal static string S_Domiciliering {
            get {
                return ResourceManager.GetString("S_Domiciliering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Frequentie.
        /// </summary>
        internal static string S_Frequentie {
            get {
                return ResourceManager.GetString("S_Frequentie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Persoon.
        /// </summary>
        internal static string S_Persoon {
            get {
                return ResourceManager.GetString("S_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Rechten.
        /// </summary>
        internal static string S_Rechten {
            get {
                return ResourceManager.GetString("S_Rechten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_RechtenCatogorie.
        /// </summary>
        internal static string S_RechtenCatogorie {
            get {
                return ResourceManager.GetString("S_RechtenCatogorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Rollen.
        /// </summary>
        internal static string S_Rollen {
            get {
                return ResourceManager.GetString("S_Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Wachtwoord.
        /// </summary>
        internal static string S_Wachtwoord {
            get {
                return ResourceManager.GetString("S_Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_WachtWoordenGroep.
        /// </summary>
        internal static string S_WachtWoordenGroep {
            get {
                return ResourceManager.GetString("S_WachtWoordenGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Account.
        /// </summary>
        internal static string U_Account {
            get {
                return ResourceManager.GetString("U_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Begunstigden.
        /// </summary>
        internal static string U_Begunstigden {
            get {
                return ResourceManager.GetString("U_Begunstigden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_BudgetCategorie.
        /// </summary>
        internal static string U_BudgetCategorie {
            get {
                return ResourceManager.GetString("U_BudgetCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Domiciliering.
        /// </summary>
        internal static string U_Domiciliering {
            get {
                return ResourceManager.GetString("U_Domiciliering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Frequentie.
        /// </summary>
        internal static string U_Frequentie {
            get {
                return ResourceManager.GetString("U_Frequentie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Persoon.
        /// </summary>
        internal static string U_Persoon {
            get {
                return ResourceManager.GetString("U_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Rollen.
        /// </summary>
        internal static string U_Rollen {
            get {
                return ResourceManager.GetString("U_Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Wachtwoord.
        /// </summary>
        internal static string U_Wachtwoord {
            get {
                return ResourceManager.GetString("U_Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_WachtWoordenGroep.
        /// </summary>
        internal static string U_WachtWoordenGroep {
            get {
                return ResourceManager.GetString("U_WachtWoordenGroep", resourceCulture);
            }
        }
    }
}
